name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' #dev-new, dev-this-is-new
      - 'feat/**' #feat/new, feat/new/button
      # developer-1 (no filter is covering this branch name)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Install dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Deploy
        run: echo "Deploying....."